# Generated by Django 4.0.4 on 2022-05-04 08:58

import apps.main.validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_delete_register'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='majorGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='نام گروه ورزشی')),
            ],
            options={
                'verbose_name': 'گروه ورزشی',
                'verbose_name_plural': 'گروه های ورزشی',
                'db_table': 'T_majorGroups',
            },
        ),
        migrations.AlterModelOptions(
            name='typepriod',
            options={'verbose_name': 'نوع دوره', 'verbose_name_plural': 'نوع دوره ها'},
        ),
        migrations.RemoveField(
            model_name='major',
            name='TypeOfMajor',
        ),
        migrations.RemoveField(
            model_name='period',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='period',
            name='majorName',
        ),
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='غیرفعال/فعال'),
        ),
        migrations.AddField(
            model_name='period',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.major', verbose_name='نام رشته'),
        ),
        migrations.AddField(
            model_name='period',
            name='periodName',
            field=models.CharField(max_length=100, null=True, verbose_name='نام دوره'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='Address',
            field=models.TextField(blank=True, max_length=200, validators=[apps.main.validation.validate_Address], verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='CoachFamily',
            field=models.CharField(blank=True, max_length=20, verbose_name='نام خانوادگی '),
        ),
        migrations.AlterField(
            model_name='coach',
            name='CoachName',
            field=models.CharField(blank=True, max_length=10, validators=[apps.main.validation.validate_name], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Man', 'مرد'), ('Female', 'زن')], max_length=40, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='majorName',
            field=models.ManyToManyField(blank=True, to='main.major', verbose_name='نام رشته '),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='major',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='major',
            name='majorName',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام رشته'),
        ),
        migrations.AlterField(
            model_name='period',
            name='typeOfPeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typepriod', verbose_name='نوع دوره'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد جلسه')),
                ('sessionName', models.CharField(max_length=20, verbose_name='نام جلسه')),
                ('TypeOfSession', models.CharField(choices=[('Normal', 'عادی'), ('reparative', 'جبرانی'), ('Extraordinary', 'فوق العاده'), ('test', 'امتحان'), ('Public holiday', 'تعطیل رسمی'), ('Special holiday', 'تعطیل خاص')], max_length=100, verbose_name='نوع جلسه')),
                ('sessionDate', models.DateField(verbose_name='تاریخ')),
                ('started_at', models.TimeField(verbose_name='شروع')),
                ('ended_at', models.TimeField(verbose_name='پایان')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.period', verbose_name='دوره')),
            ],
            options={
                'verbose_name': ' جلسه',
                'verbose_name_plural': 'جلسه ها',
                'db_table': 'T_Session',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='تاریخ')),
                ('AttendanceStatus', models.CharField(choices=[('Present', 'حاضر'), ('Delayed attendance', 'حضور با تاخیر'), ('absence', 'عدم حضور')], max_length=100, verbose_name='وضعیت حضور')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coach', verbose_name='نام استاد')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period', verbose_name='نام دوره')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': ' حضوروغیاب استاد',
                'verbose_name_plural': 'حضوروغیاب استادها',
                'db_table': 'T_AttendanceCoach',
            },
        ),
        migrations.CreateModel(
            name='AttendanceAthlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='تاریخ')),
                ('AttendanceStatus', models.CharField(choices=[('Present', 'حاضر'), ('Delayed attendance', 'حضور با تاخیر'), ('absence', 'عدم حضور')], max_length=100, verbose_name='وضعیت حضور')),
                ('Athlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.athlete', verbose_name='ورزشکار')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period', verbose_name='نام دوره')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': ' حضوروغیاب ورزشکار',
                'verbose_name_plural': 'حضوروغیاب ورزشکارها',
                'db_table': 'T_AttendanceAthlet',
            },
        ),
        migrations.AddField(
            model_name='major',
            name='MajorGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.majorgroups', verbose_name='نوع رشته ورزشی'),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaySalary', models.IntegerField(default=0, verbose_name='پرداخت هزینه')),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.athlete')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period')),
            ],
            options={
                'verbose_name': 'ورزشکار ثبت نام شده',
                'verbose_name_plural': 'ورزشکار های ثبت نام شده',
                'db_table': 'T_Register',
                'unique_together': {('period', 'athlete')},
            },
        ),
    ]
