# Generated by Django 4.0 on 2022-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_period_managers_period_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='majorName',
            field=models.ManyToManyField(blank=True, to='main.Major', verbose_name='نام رشته '),
        ),
    ]
