# Generated by Django 4.0.4 on 2022-05-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_coach_majorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancecoach',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='attendancecoach',
            name='period',
        ),
        migrations.RemoveField(
            model_name='attendancecoach',
            name='session',
        ),
        migrations.RemoveField(
            model_name='period',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='period',
            name='major',
        ),
        migrations.RemoveField(
            model_name='period',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='period',
            name='typeOfPeriod',
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='register',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='register',
            name='period',
        ),
        migrations.RemoveField(
            model_name='session',
            name='period',
        ),
        migrations.DeleteModel(
            name='AttendanceAthlet',
        ),
        migrations.DeleteModel(
            name='AttendanceCoach',
        ),
        migrations.DeleteModel(
            name='period',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
