# Generated by Django 4.0.4 on 2022-05-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_attendancecoach_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodName', models.CharField(max_length=100, null=True, verbose_name='نام دوره')),
                ('salary', models.IntegerField(default=0, verbose_name='شهریه')),
                ('Capacity', models.IntegerField(default=0, verbose_name='ظرفیت')),
                ('startDate_at', models.DateField(verbose_name='تاریخ شروع')),
                ('timestarted_at', models.TimeField(verbose_name='زمان شروع')),
                ('timeended_at', models.TimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='غیرفعال/فعال')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.coach', verbose_name='نام استاد')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.major', verbose_name='نام رشته')),
                ('salon', models.ForeignKey(default='salon', on_delete=django.db.models.deletion.CASCADE, to='main.salon', verbose_name='سالن')),
                ('typeOfPeriod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typepriod', verbose_name='نوع دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'db_table': 'T_period',
            },
        ),
    ]
