# Generated by Django 4.0.4 on 2022-05-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_period_major'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='majorgroups',
            table='T_ majorGroups',
        ),
    ]
