# Generated by Django 4.0.4 on 2022-04-15 14:04

import apps.main.validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[apps.main.validation.validate_name], verbose_name='نام')),
                ('family', models.CharField(max_length=20, validators=[apps.main.validation.validate_name], verbose_name='نام خانوادگی')),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40, message='Age can not be more than 40'), django.core.validators.MinValueValidator(5, message='Age can not be less than 5')], verbose_name='سن')),
                ('Address', models.TextField(max_length=200, validators=[apps.main.validation.validate_Address], verbose_name='آدرس')),
                ('Gender', models.CharField(choices=[('Man', 'مرد'), ('Female', 'زن')], max_length=40, verbose_name='جنسیت')),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('slug', models.SlugField(max_length=100)),
                ('gad', models.IntegerField(null=True, verbose_name='قد')),
                ('vazn', models.IntegerField(null=True, verbose_name='وزن')),
            ],
            options={
                'verbose_name': 'ورزشکار',
                'verbose_name_plural': 'ورزشکار ها',
                'db_table': 'T_athlete',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaySalary', models.IntegerField(default=0, verbose_name='پرداخت هزینه')),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.athlete')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period')),
            ],
        ),
    ]
